version: "3.8"

services:
  timetable:
    build: .
    image: timetable_container
    volumes:
      - ./src:/app/src
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - timetable
